// ============================================================
// POOKAL WHOLESALE - DATA LAYER
// Every text field that appears in the UI has both
// Tamil (ta) and English (en) versions.
// tamilName      → product name in Tamil mode
// thanglishName  → product name in English mode (Thanglish)
// englishName    → for search + admin only
// description    → Tamil description
// descriptionEn  → English description
// colors         → Tamil color names array
// colorsEn       → English color names array (same order)
// ============================================================

const SHOP_CONFIG = {
  name:           "பூக்கள் மொத்த விற்பனை",
  nameEn:         "Pookal Wholesale",
  tagline:        "புதுமையான பூக்கள் · நேரடி தோட்டத்திலிருந்து",
  taglineEn:      "Fresh Flowers · Direct from Farm",
  phone:          "+91 98765 43210",
  whatsapp:       "+91 98765 43210",
  address:        "பூக்கடை தெரு, கோயம்புத்தூர் - 641001",
  openTime:       "05:00",
  closeTime:      "21:00",
  deliveryRadius: "15 km",
  currency:       "₹",
  gst:            0,
};

// ============================================================
// DELIVERY ESTIMATE OPTIONS
// ============================================================
const DELIVERY_ESTIMATES = [
  { id: "1hr",       label: "1 மணி நேரத்தில்",    labelEn: "Within 1 hour" },
  { id: "2hr",       label: "2 மணி நேரத்தில்",    labelEn: "Within 2 hours" },
  { id: "3hr",       label: "3 மணி நேரத்தில்",    labelEn: "Within 3 hours" },
  { id: "sameday",   label: "இன்றே",               labelEn: "Same day" },
  { id: "nextday",   label: "நாளை",                labelEn: "Next day" },
  { id: "scheduled", label: "திட்டமிட்ட தேதி",    labelEn: "Scheduled date" },
  { id: "eventdate", label: "நிகழ்வு தேதியன்று",  labelEn: "On event date" },
];

// ============================================================
// FLOWERS CATEGORY
// ============================================================
const FLOWERS = [
  {
    id: "fl-001",
    tamilName: "ரோஜா",
    thanglishName: "Roja",
    englishName: "Rose",
    category: "flowers",
    description: "தரமான நாட்டு ரோஜா பூக்கள். சிவப்பு, மஞ்சள், வெள்ளை வகைகள்.",
    descriptionEn: "Premium quality country roses. Available in red, yellow, and white varieties.",
    price: 350,
    unit: "kg",
    minimumQuantity: 1,
    stock: 50,
    stockUnit: "kg",
    deliveryEstimate: "1hr",
    availability: true,
    badge: "bestseller",
    colors:   ["சிவப்பு", "மஞ்சள்", "வெள்ளை", "இளஞ்சிவப்பு"],
    colorsEn: ["Red",     "Yellow",  "White",   "Pink"],
    image: "https://thursd.com/storage/media/63575/United-Selections-Rose-Madam-Red.jpg",
    imageAlt: "Fresh red roses",
  },
  {
    id: "fl-002",
    tamilName: "மல்லிகை",
    thanglishName: "Malligai",
    englishName: "Jasmine",
    category: "flowers",
    description: "மணம் மிகுந்த மல்லிகை பூக்கள். பூஜை மற்றும் அலங்காரத்திற்கு ஏற்றது.",
    descriptionEn: "Fragrant jasmine flowers. Perfect for puja, decoration, and hair adornment.",
    price: 400,
    unit: "kg",
    minimumQuantity: 0.5,
    stock: 30,
    stockUnit: "kg",
    deliveryEstimate: "1hr",
    availability: true,
    badge: "popular",
    colors:   ["வெள்ளை"],
    colorsEn: ["White"],
    image: "https://tse2.mm.bing.net/th/id/OIP.kZL4ITnzhKDiqjfU-jjM4wHaE8?r=0&rs=1&pid=ImgDetMain&o=7&rm=3",
    imageAlt: "Fresh jasmine flowers",
  },
  {
    id: "fl-003",
    tamilName: "முல்லை",
    thanglishName: "Mullai",
    englishName: "Arabian Jasmine",
    category: "flowers",
    description: "இனிய மணமுள்ள முல்லை பூக்கள். மாலை தொடுக்க சிறந்தது.",
    descriptionEn: "Sweetly fragrant Mullai flowers. Ideal for making garlands.",
    price: 500,
    unit: "kg",
    minimumQuantity: 0.5,
    stock: 20,
    stockUnit: "kg",
    deliveryEstimate: "2hr",
    availability: true,
    badge: null,
    colors:   ["வெள்ளை"],
    colorsEn: ["White"],
    image: "https://pookadai.com/cdn/shop/files/IMG_0399.png?v=1770443968&width=940",
    imageAlt: "Mullai flowers",
  },
  {
    id: "fl-004",
    tamilName: "சாமந்தி",
    thanglishName: "Samanthi",
    englishName: "Chrysanthemum",
    category: "flowers",
    description: "பசுமையான சாமந்தி பூக்கள். திருமண அலங்காரத்திற்கு மிகவும் பயன்படும்.",
    descriptionEn: "Fresh Samanthi flowers. Very commonly used for wedding decoration.",
    price: 180,
    unit: "kg",
    minimumQuantity: 1,
    stock: 60,
    stockUnit: "kg",
    deliveryEstimate: "1hr",
    availability: true,
    badge: "fresh",
    colors:   ["வெள்ளை", "மஞ்சள்", "ஆரஞ்சு"],
    colorsEn: ["White",  "Yellow",  "Orange"],
    image: "https://m.media-amazon.com/images/I/714dIpmEa5L._SL1080_.jpg",
    imageAlt: "Chrysanthemum flowers",
  },
  {
    id: "fl-005",
    tamilName: "செவ்வந்தி",
    thanglishName: "Sevvanthi",
    englishName: "Marigold",
    category: "flowers",
    description: "கோவில் பூஜை மற்றும் அலங்காரத்திற்கு ஏற்ற செவ்வந்தி பூக்கள்.",
    descriptionEn: "Sevvanthi flowers ideal for temple puja and event decoration.",
    price: 120,
    unit: "kg",
    minimumQuantity: 1,
    stock: 100,
    stockUnit: "kg",
    deliveryEstimate: "1hr",
    availability: true,
    badge: "offer",
    colors:   ["மஞ்சள்", "ஆரஞ்சு"],
    colorsEn: ["Yellow",  "Orange"],
    image: "https://tse3.mm.bing.net/th/id/OIP.mDnZjyeE1V-_xT5xOhucrwHaFM?r=0&rs=1&pid=ImgDetMain&o=7&rm=3",
    imageAlt: "Marigold flowers",
  },
  {
    id: "fl-006",
    tamilName: "கனகாம்பரம்",
    thanglishName: "Kanakambaram",
    englishName: "Crossandra",
    category: "flowers",
    description: "சிவப்பு-ஆரஞ்சு நிற கனகாம்பர பூக்கள். அலங்காரத்திற்கும் மாலைக்கும் பயன்படும்.",
    descriptionEn: "Orange-red Kanakambaram flowers. Used for decoration and garland making.",
    price: 600,
    unit: "kg",
    minimumQuantity: 0.5,
    stock: 15,
    stockUnit: "kg",
    deliveryEstimate: "2hr",
    availability: true,
    badge: "premium",
    colors:   ["ஆரஞ்சு-சிவப்பு"],
    colorsEn: ["Orange-Red"],
    image: "https://images.unsplash.com/photo-1490750967868-88df5691cc97?w=400&q=80",
    imageAlt: "Crossandra flowers",
  },
  {
    id: "fl-007",
    tamilName: "சம்பங்கி",
    thanglishName: "Sampangi",
    englishName: "Champak",
    category: "flowers",
    description: "மணமிக்க சம்பங்கி பூக்கள். பூஜை மற்றும் கூந்தல் அலங்காரத்திற்கு ஏற்றது.",
    descriptionEn: "Fragrant Sampangi flowers. Great for puja and hair decoration.",
    price: 800,
    unit: "kg",
    minimumQuantity: 0.25,
    stock: 10,
    stockUnit: "kg",
    deliveryEstimate: "2hr",
    availability: true,
    badge: "premium",
    colors:   ["மஞ்சள்-வெள்ளை"],
    colorsEn: ["Yellow-White"],
    image: "https://i1.wp.com/i.ytimg.com/vi/tSwZh7ySaEw/maxresdefault.jpg?resize=820%2C461&ssl=1",
    imageAlt: "Champak flowers",
  },
  {
    id: "fl-008",
    tamilName: "தாமரை",
    thanglishName: "Thaamarai",
    englishName: "Lotus",
    category: "flowers",
    description: "புனிதமான தாமரை பூக்கள். கோவில் பூஜைக்கு சிறந்தது.",
    descriptionEn: "Sacred Thaamarai flowers. Best suited for temple puja offerings.",
    price: 250,
    unit: "bundle",
    minimumQuantity: 1,
    stock: 25,
    stockUnit: "bundles",
    deliveryEstimate: "2hr",
    availability: true,
    badge: "sacred",
    colors:   ["இளஞ்சிவப்பு", "வெள்ளை"],
    colorsEn: ["Pink",         "White"],
    image: "https://tse1.explicit.bing.net/th/id/OIP.zMyCDP6mpkkJp-NAOgOAgQHaF7?r=0&rs=1&pid=ImgDetMain&o=7&rm=3",
    imageAlt: "Lotus flowers",
  },
  {
    id: "fl-009",
    tamilName: "பிச்சிப்பூ",
    thanglishName: "Pichipoo",
    englishName: "Tuberose",
    category: "flowers",
    description: "வெண்மையான பிச்சிப்பூ. திருமண மாலை மற்றும் அலங்காரத்திற்கு சிறந்தது.",
    descriptionEn: "Pure white Pichipoo flowers. Excellent for wedding garlands and decoration.",
    price: 450,
    unit: "kg",
    minimumQuantity: 0.5,
    stock: 18,
    stockUnit: "kg",
    deliveryEstimate: "2hr",
    availability: true,
    badge: null,
    colors:   ["வெள்ளை"],
    colorsEn: ["White"],
    image: "https://tse1.mm.bing.net/th/id/OIP.1akavKalqnchMh4oB2mfagHaE7?r=0&rs=1&pid=ImgDetMain&o=7&rm=3",
    imageAlt: "Tuberose flowers",
  },
];

// ============================================================
// BOUQUETS CATEGORY
// sizes have labelTa (Tamil) and labelEn (English)
// preparationTime has ta and en fields
// description + descriptionEn
// ============================================================
const BOUQUETS = [
  {
    id: "bq-001",
    tamilName: "சிவப்பு ரோஜா பூங்கொத்து",
    thanglishName: "Sivappu Roja Poongothu",
    englishName: "Red Rose Bouquet",
    category: "bouquets",
    description:   "தரமான சிவப்பு ரோஜாக்களால் ஆன அழகான பூங்கொத்து. காதல் மற்றும் சிறப்பு நிகழ்வுகளுக்கு ஏற்றது.",
    descriptionEn: "A beautiful bouquet of premium red roses. Perfect for love and special occasions.",
    sizes: {
      small:  { labelTa: "சிறியது (12 ரோஜா)",   labelEn: "Small (12 Roses)",  price: 350,  flowers: 12 },
      medium: { labelTa: "நடுத்தரம் (24 ரோஜா)", labelEn: "Medium (24 Roses)", price: 650,  flowers: 24 },
      large:  { labelTa: "பெரியது (50 ரோஜா)",   labelEn: "Large (50 Roses)",  price: 1200, flowers: 50 },
    },
    unit: "bouquet",
    minimumQuantity: 1,
    preparationTime: { ta: "45 நிமிடங்கள்", en: "45 mins" },
    sameDayDelivery: true,
    availability: true,
    badge: "bestseller",
    image: "https://storage.googleapis.com/regalflowers-cdn/img-2022-07-Regal-Red-Roses-Bouquet_11zon-1-scaled.jpg",
    imageAlt: "Red rose bouquet",
  },
  {
    id: "bq-002",
    tamilName: "கலப்பு மலர் பூங்கொத்து",
    thanglishName: "Kalappu Malar Poongothu",
    englishName: "Mixed Flower Bouquet",
    category: "bouquets",
    description:   "பல்வேறு வண்ண பூக்களால் ஆன இனிமையான கலப்பு பூங்கொத்து.",
    descriptionEn: "A delightful mixed bouquet with flowers in a variety of colors.",
    sizes: {
      small:  { labelTa: "சிறியது",   labelEn: "Small",  price: 280, flowers: 15 },
      medium: { labelTa: "நடுத்தரம்", labelEn: "Medium", price: 520, flowers: 30 },
      large:  { labelTa: "பெரியது",   labelEn: "Large",  price: 950, flowers: 60 },
    },
    unit: "bouquet",
    minimumQuantity: 1,
    preparationTime: { ta: "30 நிமிடங்கள்", en: "30 mins" },
    sameDayDelivery: true,
    availability: true,
    badge: "popular",
    image: "https://tse1.mm.bing.net/th/id/OIP.hvP6_MifhNo-nnYo9mhUkQHaHa?r=0&rs=1&pid=ImgDetMain&o=7&rm=3",
    imageAlt: "Mixed flower bouquet",
  },
  {
    id: "bq-003",
    tamilName: "பிறந்தநாள் பூங்கொத்து",
    thanglishName: "Pirandhanaal Poongothu",
    englishName: "Birthday Bouquet",
    category: "bouquets",
    description:   "பிறந்தநாள் கொண்டாட்டத்திற்கு சிறப்பான வண்ணமயமான பூங்கொத்து. Happy Birthday செய்தி அட்டை இலவசம்.",
    descriptionEn: "Colorful birthday bouquet with a free Happy Birthday message card included.",
    sizes: {
      small:  { labelTa: "சிறியது",   labelEn: "Small",  price: 320,  flowers: 15 },
      medium: { labelTa: "நடுத்தரம்", labelEn: "Medium", price: 580,  flowers: 28 },
      large:  { labelTa: "பெரியது",   labelEn: "Large",  price: 1100, flowers: 55 },
    },
    unit: "bouquet",
    minimumQuantity: 1,
    preparationTime: { ta: "1 மணி நேரம்", en: "1 hour" },
    sameDayDelivery: true,
    availability: true,
    badge: "gift",
    image: "https://cdn.uaeflowers.com/uploads/product/AUG2025/HappyBirthdayRosesBouquet-1755771151595.webp",
    imageAlt: "Birthday bouquet",
  },
  {
    id: "bq-004",
    tamilName: "வாழ்த்து பூங்கொத்து",
    thanglishName: "Vaazhthu Poongothu",
    englishName: "Congratulations Bouquet",
    category: "bouquets",
    description:   "வெற்றி, பதவி ஏற்பு, திருமணம் போன்ற சந்தோஷ நிகழ்வுகளுக்கு வாழ்த்து பூங்கொத்து.",
    descriptionEn: "Congratulations bouquet for victories, promotions, weddings, and joyful events.",
    sizes: {
      small:  { labelTa: "சிறியது",   labelEn: "Small",  price: 400,  flowers: 20 },
      medium: { labelTa: "நடுத்தரம்", labelEn: "Medium", price: 750,  flowers: 40 },
      large:  { labelTa: "பெரியது",   labelEn: "Large",  price: 1400, flowers: 75 },
    },
    unit: "bouquet",
    minimumQuantity: 1,
    preparationTime: { ta: "45 நிமிடங்கள்", en: "45 mins" },
    sameDayDelivery: true,
    availability: true,
    badge: "special",
    image: "https://static-assets-prod.fnp.com/images/pr/l/v20220706181718/admire-the-beauty-roses-bouquet_1.jpg",
    imageAlt: "Congratulations bouquet",
  },
 
  {
    id: "bq-007",
    tamilName: "சூரியகாந்தி பூங்கொத்து",
    thanglishName: "Sooriyakanthi Poongothu",
    englishName: "Sunflower Bouquet",
    category: "bouquets",
    description:   "பொன் நிற சூரியகாந்தி பூங்கொத்து. சந்தோஷ நிகழ்வுகளுக்கு ஏற்றது.",
    descriptionEn: "Golden Sooriyakanthi bouquet. Perfect for cheerful and joyful occasions.",
    sizes: {
      small:  { labelTa: "சிறியது (5 பூக்கள்)",   labelEn: "Small (5 flowers)",  price: 380,  flowers: 5  },
      medium: { labelTa: "நடுத்தரம் (10 பூக்கள்)", labelEn: "Medium (10 flowers)", price: 700,  flowers: 10 },
      large:  { labelTa: "பெரியது (20 பூக்கள்)",  labelEn: "Large (20 flowers)",  price: 1300, flowers: 20 },
    },
    unit: "bouquet",
    minimumQuantity: 1,
    preparationTime: { ta: "45 நிமிடங்கள்", en: "45 mins" },
    sameDayDelivery: true,
    availability: true,
    badge: null,
    image: "https://tse1.mm.bing.net/th/id/OIP.PuLPbAJLiLTcMA4N-m2PcAHaHa?r=0&rs=1&pid=ImgDetMain&o=7&rm=3",
    imageAlt: "Sunflower bouquet",
  },
];

// ============================================================
// WEDDING DECOR CATEGORY
// services, turnaroundTime, description all have English versions
// ============================================================
const WEDDING_DECOR = [
  {
    id: "wd-001",
    tamilName: "திருமண மேடை அலங்காரம்",
    thanglishName: "Thirumana Medai Alangaram",
    englishName: "Wedding Stage Decoration",
    category: "weddingDecor",
    description:   "பாரம்பரிய மற்றும் நவீன நடை திருமண மேடை அலங்காரம். ரோஜா, மல்லிகை, சாமந்தி பூக்கள் பயன்படுத்தப்படும். LED விளக்குகள் மற்றும் துணி அலங்காரம் சேர்க்கப்படும்.",
    descriptionEn: "Traditional and modern style wedding stage decoration using Roja, Malligai, and Samanthi flowers with LED lights and fabric draping.",
    startingPrice: 15000,
    unit: "per event",
    services:   ["பூ அலங்காரம்",          "LED விளக்கு அலங்காரம்", "துணி அலங்காரம்",  "Backdrop"],
    servicesEn: ["Flower decoration",    "LED light decoration",   "Fabric draping",  "Backdrop"],
    availability: true,
    requiresQuote: true,
    badge: "premium",
    turnaroundTime:   "நிகழ்வுக்கு 1 நாள் முன்பு",
    turnaroundTimeEn: "1 day before event",
    image: "https://th.bing.com/th/id/OIP.eoLF6CYYcY8Eay843Lx5LAHaE4?r=0&o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3",
    imageAlt: "Wedding stage decoration",
  },
  {
    id: "wd-002",
    tamilName: "நுழைவாயில் அலங்காரம்",
    thanglishName: "Nuzhaivaayil Alangaram",
    englishName: "Entrance Gate Decoration",
    category: "weddingDecor",
    description:   "திருமண வரவேற்பு நுழைவாயில் அலங்காரம். பல்வேறு வண்ண பூக்கள் மற்றும் மல்லிகை கர்ட்டன் அலங்காரம்.",
    descriptionEn: "Wedding entrance gate decoration with colorful flowers and a Malligai flower curtain.",
    startingPrice: 5000,
    unit: "per gate",
    services:   ["பூ தோரணம்",     "மல்லிகை கர்ட்டன்",   "LED அலங்காரம்",   "பனை மர அலங்காரம்"],
    servicesEn: ["Flower arch",   "Malligai curtain",    "LED decoration",  "Palm tree decoration"],
    availability: true,
    requiresQuote: true,
    badge: "popular",
    turnaroundTime:   "நிகழ்வு தினத்தன்று",
    turnaroundTimeEn: "On event day",
    image: "https://tse4.mm.bing.net/th/id/OIP.Xq8jqxx-I_8wXaPefhL43gHaJn?r=0&rs=1&pid=ImgDetMain&o=7&rm=3",
    imageAlt: "Wedding entrance decoration",
  },
  {
    id: "wd-004",
    tamilName: "மணமக்கள் பூமாலை",
    thanglishName: "Manamakkal Poomaalai",
    englishName: "Bridal Garland",
    category: "weddingDecor",
    description:   "மணமகன் மற்றும் மணமகளுக்கான தனிப்பட்ட பூமாலை. மல்லிகை, ரோஜா, பிச்சிப்பூ கலவை.",
    descriptionEn: "Custom bridal garlands for bride and groom made with Malligai, Roja, and Pichipoo flowers.",
    startingPrice: 800,
    unit: "pair",
    services:   ["மணமகன் மாலை",   "மணமகள் மாலை",   "தனிப்பயன் அலங்காரம்"],
    servicesEn: ["Groom garland",  "Bride garland",  "Custom decoration"],
    availability: true,
    requiresQuote: false,
    badge: "must-have",
    turnaroundTime:   "திருமண நாளன்று காலை",
    turnaroundTimeEn: "On wedding morning",
    image: "https://i.pinimg.com/originals/e9/55/54/e95554380df34c8b9da8171b4e66e0a3.jpg",
    imageAlt: "Bridal garland",
  },
  {
    id: "wd-005",
    tamilName: "வரவேற்பு அலங்காரம்",
    thanglishName: "Varaverpu Alangaram",
    englishName: "Reception Hall Decoration",
    category: "weddingDecor",
    description:   "திருமண வரவேற்பு மண்டப அலங்காரம். மேசை மற்றும் நாற்காலி அலங்காரம் உட்பட.",
    descriptionEn: "Wedding reception hall decoration including stage, table, and chair arrangements.",
    startingPrice: 20000,
    unit: "per hall",
    services:   ["மேடை அலங்காரம்",    "மேசை அலங்காரம்",   "நாற்காலி அலங்காரம்",  "மையப் புள்ளி அலங்காரம்"],
    servicesEn: ["Stage decoration",  "Table decoration",  "Chair decoration",     "Centerpiece decoration"],
    availability: true,
    requiresQuote: true,
    badge: "premium",
    turnaroundTime:   "நிகழ்வுக்கு 1 நாள் முன்பு",
    turnaroundTimeEn: "1 day before event",
    image: "https://i.pinimg.com/originals/79/2f/e2/792fe2ffdb4116ee8baf99486d8ce0f5.jpg",
    imageAlt: "Reception hall decoration",
  },
  {
    id: "wd-007",
    tamilName: "போட்டோ பூத் அலங்காரம்",
    thanglishName: "Photo Booth Alangaram",
    englishName: "Photo Booth Decoration",
    category: "weddingDecor",
    description:   "திருமண புகைப்பட புத்தகத்திற்கான சிறப்பான பூ அலங்கரிக்கப்பட்ட போட்டோ பூத்.",
    descriptionEn: "Beautifully flower-decorated photo booth for your wedding album.",
    startingPrice: 4000,
    unit: "per setup",
    services:   ["பூ சுவர்",      "பெயர் பலகை",   "Props",  "LED lights"],
    servicesEn: ["Flower wall",   "Name board",    "Props",  "LED lights"],
    availability: true,
    requiresQuote: true,
    badge: "trending",
    turnaroundTime:   "நிகழ்வுக்கு 3 மணி நேரம் முன்பு",
    turnaroundTimeEn: "3 hours before event",
    image: "https://i.pinimg.com/originals/57/24/8c/57248c7b9133a057db0db01e2728f3fc.jpg",
    imageAlt: "Photo booth decoration",
  },
];

// ============================================================
// CUSTOMIZATION REQUEST TYPES (bilingual label)
// ============================================================
const CUSTOMIZATION_TYPES = [
  { id: "mala",    label: "மாலை தயாரிப்பு",       labelEn: "Maalai Customization",    icon: "🌸" },
  { id: "bouquet", label: "பூங்கொத்து தயாரிப்பு",  labelEn: "Bouquet Customization",   icon: "💐" },
  { id: "wedding", label: "திருமண அலங்காரம்",       labelEn: "Thirumana Alangaram",      icon: "💒" },
  { id: "car",     label: "கார் அலங்காரம்",          labelEn: "Car Alangaram",            icon: "🚗" },
  { id: "pooja",   label: "பூஜை பூ அலங்காரம்",      labelEn: "Pooja Poo Alangaram",      icon: "🙏" },
  { id: "other",   label: "மற்ற கோரிக்கை",           labelEn: "Other Request",            icon: "✨" },
];

const FLOWER_OPTIONS = [
  "ரோஜா", "மல்லிகை", "முல்லை", "சாமந்தி", "செவ்வந்தி",
  "கனகாம்பரம்", "சம்பங்கி", "தாமரை", "பிச்சிப்பூ", "ஜெர்பரா",
  "சூரியகாந்தி", "ஆர்க்கிட்", "லில்லி", "கலப்பு பூக்கள்",
];

const COLOR_OPTIONS = [
  { label: "சிவப்பு",        labelEn: "Red",           value: "red",    hex: "#e53e3e" },
  { label: "வெள்ளை",         labelEn: "White",          value: "white",  hex: "#f7fafc" },
  { label: "மஞ்சள்",         labelEn: "Yellow",         value: "yellow", hex: "#ecc94b" },
  { label: "இளஞ்சிவப்பு",   labelEn: "Pink",           value: "pink",   hex: "#f687b3" },
  { label: "ஆரஞ்சு",         labelEn: "Orange",         value: "orange", hex: "#ed8936" },
  { label: "ஊதா",            labelEn: "Purple",         value: "purple", hex: "#9f7aea" },
  { label: "நீலம்",          labelEn: "Blue",           value: "blue",   hex: "#4299e1" },
  { label: "பச்சை",          labelEn: "Green",          value: "green",  hex: "#48bb78" },
  { label: "கலப்பு நிறங்கள்", labelEn: "Mixed Colors", value: "mixed",  hex: "linear-gradient(135deg, #f6d365 0%, #fda085 100%)" },
];

// ============================================================
// ORDER STATUS CONFIGS
// ============================================================
const ORDER_STATUSES = {
  flowers: [
    { id: "placed",           label: "ஆர்டர் பெறப்பட்டது",         labelEn: "Order Placed",      icon: "📋" },
    { id: "confirmed",        label: "கடை உறுதிப்படுத்தியது",       labelEn: "Shop Confirmed",    icon: "✅" },
    { id: "packing",          label: "பொட்டலம் கட்டுகிறோம்",        labelEn: "Packing",           icon: "📦" },
    { id: "out_for_delivery", label: "வழியில் உள்ளது",               labelEn: "Out for Delivery",  icon: "🛵" },
    { id: "delivered",        label: "வழங்கப்பட்டது",                labelEn: "Delivered",         icon: "🏠" },
  ],
  bouquets: [
    { id: "placed",           label: "ஆர்டர் பெறப்பட்டது",          labelEn: "Order Placed",      icon: "📋" },
    { id: "confirmed",        label: "உறுதிப்படுத்தப்பட்டது",        labelEn: "Confirmed",         icon: "✅" },
    { id: "preparing",        label: "பூங்கொத்து தயாரிக்கிறோம்",    labelEn: "Preparing",         icon: "💐" },
    { id: "ready",            label: "தயார்",                         labelEn: "Ready",             icon: "🎁" },
    { id: "out_for_delivery", label: "வழியில் உள்ளது",               labelEn: "Out for Delivery",  icon: "🛵" },
    { id: "delivered",        label: "வழங்கப்பட்டது",                labelEn: "Delivered",         icon: "🏠" },
  ],
  weddingDecor: [
    { id: "received",         label: "பதிவு பெறப்பட்டது",            labelEn: "Booking Received",  icon: "📋" },
    { id: "review",           label: "மதிப்பீட்டில் உள்ளது",         labelEn: "Under Review",      icon: "🔍" },
    { id: "quotation_sent",   label: "மதிப்பீடு அனுப்பப்பட்டது",    labelEn: "Quotation Sent",    icon: "📄" },
    { id: "approved",         label: "வாடிக்கையாளர் ஒப்புதல்",       labelEn: "Approved",          icon: "✅" },
    { id: "team_assigned",    label: "குழு நியமிக்கப்பட்டது",        labelEn: "Team Assigned",     icon: "👷" },
    { id: "setup_scheduled",  label: "அமைப்பு திட்டமிடப்பட்டது",    labelEn: "Setup Scheduled",   icon: "📅" },
    { id: "completed",        label: "நிறைவேற்றப்பட்டது",            labelEn: "Completed",         icon: "🎊" },
  ],
  customization: [
    { id: "received",         label: "கோரிக்கை பெறப்பட்டது",         labelEn: "Request Received",  icon: "📋" },
    { id: "review",           label: "மதிப்பீட்டில் உள்ளது",         labelEn: "Under Review",      icon: "🔍" },
    { id: "quotation_sent",   label: "மதிப்பீடு அனுப்பப்பட்டது",    labelEn: "Quotation Sent",    icon: "📄" },
    { id: "approved",         label: "வாடிக்கையாளர் ஒப்புதல்",       labelEn: "Approved",          icon: "✅" },
    { id: "preparing",        label: "தயாரிக்கிறோம்",                 labelEn: "Preparing",         icon: "🌸" },
    { id: "delivered",        label: "தயார் / வழங்கப்பட்டது",        labelEn: "Ready / Delivered", icon: "🏠" },
  ],
};

// ============================================================
// EXPORT / GLOBAL ACCESS
// ============================================================
window.ShopData = {
  SHOP_CONFIG,
  DELIVERY_ESTIMATES,
  FLOWERS,
  BOUQUETS,
  WEDDING_DECOR,
  CUSTOMIZATION_TYPES,
  FLOWER_OPTIONS,
  COLOR_OPTIONS,
  ORDER_STATUSES,
};
